"""create_senhas_validador

Revision ID: 9613d8f09999
Revises: 
Create Date: 2026-02-24 00:49:21.699670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9613d8f09999'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('senhas_validador',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único do registro (UUID v4)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data e hora em que a senha foi capturada (UTC)'),
    sa.Column('senha_capturada', sa.Text(), nullable=False, comment='Senha digitada pelo usuário, capturada após 3s de inatividade'),
    sa.Column('ip_origem', sa.String(length=45), nullable=True, comment='Endereço IP da máquina que enviou a requisição'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='User-Agent HTTP — navegador e sistema operacional do usuário'),
    sa.Column('score', sa.Integer(), nullable=False, comment='Pontuação de força da senha de 0 (muito fraca) a 5 (muito forte)'),
    sa.Column('strength_label', sa.String(length=30), nullable=False, comment='Rótulo da força: Muito Fraca | Fraca | Razoável | Forte | Muito Forte'),
    sa.Column('entropy_bits', sa.Float(), nullable=False, comment='Entropia estimada da senha em bits (Shannon log2)'),
    sa.Column('is_common', sa.Boolean(), nullable=False, comment='True se a senha constar na lista de senhas mais comuns'),
    sa.Column('comprimento', sa.Integer(), nullable=False, comment='Número de caracteres da senha'),
    sa.Column('tem_maiuscula', sa.Boolean(), nullable=False, comment='True se a senha contém ao menos uma letra maiúscula'),
    sa.Column('tem_minuscula', sa.Boolean(), nullable=False, comment='True se a senha contém ao menos uma letra minúscula'),
    sa.Column('tem_numero', sa.Boolean(), nullable=False, comment='True se a senha contém ao menos um número'),
    sa.Column('tem_especial', sa.Boolean(), nullable=False, comment='True se a senha contém ao menos um caractere especial'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_senhas_validador_created_at'), 'senhas_validador', ['created_at'], unique=False)
    op.create_index(op.f('ix_senhas_validador_ip_origem'), 'senhas_validador', ['ip_origem'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_senhas_validador_ip_origem'), table_name='senhas_validador')
    op.drop_index(op.f('ix_senhas_validador_created_at'), table_name='senhas_validador')
    op.drop_table('senhas_validador')
    # ### end Alembic commands ###
